### PR TITLE
Check empty strings

### PR DESCRIPTION
**Pull request by chapulina**

### CODE REVIEW

**Comment by hugomatic** [comment]
1. Note: `if (this.$.ajaxItems.url == "") return` is a silent failure. Unless this happens every time and should be ignore, it would be nice to do something about it (maybe a simple console.log)

**Comment by chapulina** [comment]
I think that should be ignored, this function is called quite often, even before some variables are set. Not really an "error"

**Comment by iche033** [comment]
mmm wondering if you're ok with sneaking in this tmp patch to suppress error message:

```
diff --git a/gz-simulationq.html b/gz-simulationq.html
index 9b9f84f..12bcd8d 100644
--- a/gz-simulationq.html
+++ b/gz-simulationq.html
@@ -286,7 +286,7 @@
         },

         _herrorItems: function(err) {
-          this._errorHelper(err, "Could not connect to [" + this.url + "]")
+          // this._errorHelper(err, "Could not connect to [" + this.url + "]")
         },
```

**Comment by iche033** [comment]
nevermind, I don't think I understand the code enough to propose what I wanted to do

**Comment by chapulina** [comment]
I think it's ok to suppress that warning for now. I'll do it

**Comment by chapulina** [comment]
Done 0b390f1573fe7c81286c7118dab6117b0687d7fa

**Review by iche033 — APPROVED** [review]

**Pull request merged**
